services: 
  kong: 
    container_name: kong
    image: kong:3.5
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yaml:/kong/kong.yaml:ro